services:
  shadoop:
    image: julienlau/hadoop-single-node-cluster:3.3.3
    container_name: shadoop
    hostname: shadoop
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - /mnt/data/volumes/hadoop/:/opt/hadoop/data/shadoop
        # - ./hadoop_config:/opt/hadoop/etc/hadoop
        - ./start-hdfs.sh:/startdfs.sh
    ports:
      - "9870:9870"
      - "9000:9000"
      - "9864:9864"
      - "8088:8088"
#    command: [ "/bin/bash", "/start-hdfs.sh" ]
    networks:
      - hdfs_network

networks:
  hdfs_network:
    driver: bridge
