volumes:
  data_ingestion:
    external: true
    name: data_ingestion

networks:
  spark-network:
    driver: bridge

services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: spark-custom:3.3
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./data/:/data
      - data_ingestion:/data/ingestion
    networks:
      - spark-network

  # Spark Worker
  worker:
    image: spark-custom:3.3
    container_name: worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark
    ports:
      - "8084:8084"
    networks:
      - spark-network
