# Dockerfile.spark
FROM docker.io/bitnami/spark:3.3

USER root

# Instala curl
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Crea el directorio de JARs si no existe
RUN mkdir -p /opt/bitnami/spark/jars

# Descarga el JAR JDBC de PostgreSQL
RUN curl -L https://jdbc.postgresql.org/download/postgresql-42.7.2.jar -o /opt/bitnami/spark/jars/postgresql-42.7.2.jar

